/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class UdpEchoTest {
    @Test public void testAppHasAGreeting() {
        UdpEchoTest classUnderTest = new UdpEchoTest();
    }
}
